name: supabase_carparking_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  empty_widget: ^0.0.5
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter 
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  pretty_qr_code: ^3.3.0 
  provider: ^6.1.2
  sign_in_button: ^3.2.0 
  supabase_flutter: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/car_parking_1.jpg
    - assets/car_parking_2.jpg
    - assets/car_parking_3.jpg
    - assets/parkit.png